### ISSUE TITLE
Problem when selecting a figure the coverflow is stuck

### ISSUE THREAD

**Issue by ahmedlhanafy** [andyyou/react-coverflow#15]
There is something weird happening with me, selecting any figure works just fine except selecting the first one.
I took a look at the code that does the selection, I think you forgot to call`this._removePointerEvents();` at some point. check the links below. @andyyou 
[Link 1](https://github.com/andyyou/react-coverflow/blob/master/src/Coverflow.js#L196)
[Link2](https://github.com/andyyou/react-coverflow/blob/master/src/Coverflow.js#L204)

**Comment by andyyou** [comment]
Could you send a pr.

**Comment by andyyou** [comment]
@ahmedlhanafy I am not quite understand the problem. Is this problem happen on demo site too?

**Comment by sajumani** [comment]
When i render Item,   with loop, the grid are not clickable... even it was not active that i fixed with Timeout event but still not clickable... please help me out

<Coverflow className="cover-cnt" height={280} displayQuantityOfSide={3} navigation={true} enableHeading={false} enableScroll={true} active={this.state.active}>

{loop}
</Coverflow>

**Comment by andyyou** [comment]
Do you mean loop for `<img>` tags inside component?

**Comment by sajumani** [comment]
const girdImg = this.props.images.length > 0 ? <Coverflow /> : '';

After this works fine, i fixed ... thanks for your reply

**Comment by andyyou** [comment]
Sorry for that because I migrate to Vue so I have no subscription of this project and follow React since v0.14

**Comment by Asalem1** [comment]
Resolved with PR #32

**Comment by Asalem1** [comment]
Resolved #32
