### ISSUE TITLE
Got error Uncaught TypeError: Cannot read property 'removeEventListener' of undefined

### ISSUE THREAD

**Issue by darrylsepeda** [andyyou/react-coverflow#37]
```
componentWillUnmount() {
    let length = React.Children.count(this.props.children);

    TRANSITIONS.forEach(event => {
      for (let i = 0; i < length; i++) {
        let figureID = `figure_${i}`;
        this.refs[figureID].removeEventListener(event, HandleAnimationState.bind(this));
      }
    });
    window.removeEventListener('resize', this.updateDimensions.bind(this));
    document.removeEventListener('keypress', this._keypress.bind(this));
  }
```

I have 2 questions:

1. I got error when move from page that has react-coverflow to other page that has no react-coverflow, react-coverflow can't find `this.refs[figureID]`
Is it okay to add preventif code to check whether `this.refs[figureID]` is exist or not? or anyone has any other way of how to avoid this error?

2. I have set navigation true, the button appeared but it becomes clickable only after user scroll the coverflow. So user can't use the initial button until they use the scroll event. Does anyone have experienced the same thing?

NB: I imported react-coverflow using dynamic(). (In case there is any relation with how the way I import react-coverflow and what makes this error appear)

**Comment by Asalem1** [comment]
Hey @darrylsepeda, that's interesting. I'll take a look at this and let you know.

1. It seems like the lifecycle event might be triggering the warning before the switch (i.e. the component is unmounting, but returns an error since the event listener targets no longer persist one the DOM).

2. I'm not sure why the button would be disabled until the user has scrolled, I'll try and recreate the bug and get back to you. Thanks for reporting these
