### ISSUE TITLE
resize listener produces error if component is unmounted/remounted

### ISSUE THREAD

**Issue by phillipkerman** [andyyou/react-coverflow#40]
Issue:
I'm getting an error when I resize (if the component is unmounted/remounted):
`Uncaught Error: Unable to find node on an unmounted component.
    at invariant (invariant.js:42)
    at findCurrentFiberUsingSlowPath (react-dom.development.js:3552)
    at findCurrentHostFiber (react-dom.development.js:3621)
    at Object.findHostInstance (react-dom.development.js:12611)
    at Object.findDOMNode (react-dom.development.js:16395)
    at RadiumEnhancer.updateDimensions (CoverFlow.js:124)`

Reproduce:
1. use CoverFlow inside a component.
2. remove container component (confirm componentWillUnmount occurs)
3. curiously, notice CoverFlow DOES execute: window.removeEventListener('resize', this.updateDimensions.bind(this));
4 resize the browser window now that the CoverFlow is gone.  
5. see error above.

I could avoid the issue by never adding the resize to begin with--that is, comment out:
window.addEventListener('resize', this.updateDimensions.bind(this));

Please tell me if there's something I can do to help.

**Comment by Asalem1** [comment]
Hey Phil, I believe this is related to #37 - TLDR is that componentWillUnmount is triggered before componentWillMount (this is inherent within React https://github.com/facebook/react/issues/11106). I'm going to delve into the repo this week to see if there's a way of refactoring Coverflow so that it is independent of the window and these particular lifecycle events. I'll let you know when it's all ready to pull

**Comment by Asalem1** [comment]
Most recent version temporarily removes reference to resizing (https://github.com/andyyou/react-coverflow/commit/62085c9e6b7dcc00594ce99b34be5e45465cc9c6)
